#Atividade 3#

1. π via Monte Carlo (etapa 1) Considere um círculo de raio r=1 inscrito em um quadrado de lado 2r=2. A área do círculo é πr2=π. A área do quadrado é 4. A razão entre a área do círculo e a área do quadrado é π/4. Se gerarmos N pontos aleatórios uniformemente distribuídos no quadrado, a fração de pontos que cairão dentro do círculo será π/4. Assim, podemos estimar π como 4 vezes a fração de pontos que caíram dentro do círculo. Como visto em aula, pode considerar o círculo e quadrados completos, ou apenas o primeiro quadrante. Varie o número de pontos sorteados N para ver como o resultado muda. 

In [ ]:
import numpy as np
def pi_monte_carlo(N):
    '''
    Calcula uma estimativa de pi usando o método de Monte Carlo.
    Temos um círculo de raio 1 inscrito em um quadrado de lado 2.
    A área considerada é a do primeiro quadrante do círculo.
    A área do círculo é pi*r^2 e a do quadrado é (2r)^2 = 4.

    Args:
        N: número de pontos a serem gerados.
        Ac: Área do círculo.
        Aq: Área do quadrado.
        estimativa_pi: estimativa de pi.
    Returns:    
        estimativa_pi: estimativa de pi.
    '''

rng = np.random.default_rng(seed=42)#Gera números aleatórios
N = 100000 #Quantidade de números aleatórios gerados
x = rng.uniform(0,1,N) #pontos no eixo x
y = rng.uniform(0,1, N) #pontos no eixo y
r = np.sqrt(x**2 + y**2)
dentro = r[r <= 1]
estimativa_pi = 4*len(dentro)/N
print(estimativa_pi)

#Teste
pi_monte_carlo(200000) #Teste da função 





3.13776


In [60]:
import numpy as np
import matplotlib.pyplot as plt
def pi_monte_carlo(N, retorna_pontos = False):
    '''
    Calcula uma estimativa de pi usando o método de Monte Carlo.
    Temos um círculo de raio 1 inscrito em um quadrado de lado 2.
    A área considerada é a do primeiro quadrante do círculo.
    A área do círculo é pi*r^2 e a do quadrado é (2r)^2 = 4.


    Args:
        N: número de pontos a serem gerados.
        Ac: Área do círculo.
        Aq: Área do quadrado.
        estimativa_pi: estimativa de pi.
    Returns:    
        estimativa_pi: estimativa de pi.
        Plota gráfico com os números aleatórios
    '''




rng = np.random.default_rng(seed=42)#Gera números aleatórios
N = 100000 #Quantidade de números aleatórios gerados
x = rng.uniform(0,1,N) #pontos no eixo x
y = rng.uniform(0,1, N) #pontos no eixo y
r = np.sqrt(x**2 + y**2)
dentro = (r <= 1)
estimativa_pi = 4*sum(dentro)/N
print(estimativa_pi)

#Gráfico
retorna_pontos = True
plt.figure(figsize=(6,6))
for i in range(N):
    if r[i] <= 1:
       x = np.linspace(0,1,100, color = 'blue')
       y = n.linspace(0,1,100, color = 'blue')
         plt.plot(x,y)
    else:
       x = np.linspace(0,1,100, color = 'red')
       y = n.linspace(0,1,100, color = 'red')
            plt.plot(x,y) 

plt.title('Estimativa de pi: {}'.format(estimativa_pi))
plt.xlabel('x')
plt.ylabel('y')
plt.plot()
plt.gca().set_aspect('equal')

#retorna pontos
#if retorna_pontos:
 #     return estimativa_pi, dentro, fora
 #   else:
 #       return estimativa_pi

#Arrumar eixos:
#caso 1 (todos os eixos)
#  plt.plot(...)
#  plt.gca().set_aspect('equal')

#caso 2 (cada eixo)
#  ax.plot(...)
#  ax.set_aspect('equal')


#Teste
pi_monte_carlo(2000) #Teste da função 

IndentationError: unexpected indent (3662389081.py, line 40)

In [55]:
%timeit estimativa_pi = pi_monte_carlo(1000000) #Teste de tempo da função

74.5 ns ± 1.56 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [ ]:
dentro = []
x = [1,2,3, 4, 5, 6]
y = [7,8,9,10,11,12]

print('x:', x)
print('y:', y)

dentro.append([x[0],y[0]])

dentro.append([x[3],y[3]])

dentro.append([x[4],y[4]])

dentro = np.array(dentro)

print('Dentro:\n', dentro)

x: [1, 2, 3, 4, 5, 6]
y: [7, 8, 9, 10, 11, 12]
Dentro:
 [[ 1  7]
 [ 4 10]
 [ 5 11]]


In [ ]:
retorna_ponto.append([x[0],y[0]])

dentro = np.array(dentro)
x = np.linspace(0 ,1,  200)
y = np.linspace(0 ,1,  200)


(3, 2)

In [41]:
dentro[:, 0]

array([1, 4, 5])

In [42]:
dentro[:, 1]

array([ 7, 10, 11])

In [43]:
dentro[0,:]

array([1, 7])

In [44]:
dentro[1,:]

array([ 4, 10])